name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        tags: ['', 'netlib', 'nonetlib']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
        
    - name: Install openblas on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libopenblas-dev

    - name: Install openblas on MacOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install openblas
        echo 'CGO_LDFLAGS="-L/opt/homebrew/opt/openblas/lib"' >> $GITHUB_ENV

    - name: Run tests
      run: |
        if [ "${{ matrix.tags }}" != "" ]; then
          go test -v -tags=${{ matrix.tags }} ./...
          go test -v -tags=${{ matrix.tags }} -bench=. -run=^$ ./...
        else
          go test -v ./...
          go test -v -bench=. -run=^$ ./...
        fi
 